version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    container_name: salao-frontend
    ports:
      - "80:80"
    restart: unless-stopped

    # For development with hot-reload, uncomment these lines:
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # command: npm run dev
    # ports:
    #   - "5173:5173"
    
