version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salao-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    # For development with hot-reload, uncomment these lines:
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # command: npm run dev
    # ports:
    #   - "5173:5173"
    environment:
      - NODE_ENV=production
      # Add any environment variables needed for the frontend
      # - VITE_API_URL=http://backend:8000
