version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: salao-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add any environment variables needed for development
      # - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
